# data_generation.py
import random

def generate_texts_labels(num_samples):
    positive_texts = [
        "Ich fühle mich so glücklich heute.",
        "Diese Blumen bringen Farbe in meinen Tag.",
        "Die Musik macht meine Stimmung noch besser.",
        "Ich bin dankbar für die kleinen Freuden im Leben.",
        "Ein Lächeln kann den Tag verändern.",
        "Die Sonne scheint, und alles fühlt sich gut an.",
        "In guter Gesellschaft ist alles schöner.",
        "Ein herzhaftes Lachen ist die beste Medizin.",
        "Jeder Tag ist eine neue Gelegenheit zum Glücklichsein.",
        "Positive Gedanken schaffen positive Realität.",
        "Ich schätze die kleinen Momente des Glücks.",
        "Mit positiver Energie kann ich alles schaffen.",
        "Die Welt ist voller Möglichkeiten und Chancen.",
        "Gelassenheit bringt inneren Frieden.",
        "Ein erfolgreiches Tag beginnt mit einem positiven Denken.",
        "Die Liebe meiner Familie macht alles besser.",
        "Gute Freunde sind wie Sterne in meinem Leben.",
        "Ich bin stolz auf meine Erfolge.",
        "Ich bin umgeben von Liebe und Wärme.",
        "Jeder Tag ist eine neue Chance, mein Bestes zu geben.",
        "Ich liebe die Herausforderungen, die das Leben bietet.",
        "Gutes Essen und gute Gesellschaft sind unschlagbar.",
        "Dankbarkeit ist der Schlüssel zum Glück.",
        "Die Natur hat eine beruhigende Wirkung auf mich.",
        "Ich freue mich auf die kommenden Abenteuer.",
        "Ich bin inspiriert von der Schönheit um mich herum.",
        "Erfolg ist eine Reise, nicht nur ein Ziel.",
        "Jeder Tag bringt neue Lektionen und Möglichkeiten.",
        "Meine Träume sind die Treibstoffe meiner Motivation.",
        "Ich strahle positive Energie aus.",
        "Ich bin dankbar für meine Gesundheit und Wohlbefinden.",
        "Die besten Dinge im Leben sind oft die einfachsten.",
        "Mein Optimismus öffnet Türen zu neuen Horizonten.",
        "Ich bin der Architekt meines eigenen Glücks.",
        "Jeder Tag ist ein Geschenk, das ich schätze.",
        "Das Leben ist ein Abenteuer, das ich gerne erlebe.",
        "Ich bin umgeben von Liebe und Positivität.",
        "Heute ist der perfekte Tag, um glücklich zu sein.",
        "Ich bin mutig und überwinde Herausforderungen.",
        "Ich vertraue darauf, dass alles gut wird.",
        "Ich freue mich auf die positiven Veränderungen.",
        "Ich liebe es, Zeit mit meiner Familie zu verbringen.",
        "Ich strahle Freude und Liebe aus.",
        "Die besten Dinge im Leben sind unsichtbar.",
        "Mein Herz ist voller Dankbarkeit.",
        "Ich bin ein Schöpfer meines eigenen Glücks.",
        "Jeder Tag bringt neue Möglichkeiten zur Entfaltung.",
        "Ich bin der Architekt meines eigenen Schicksals.",
        "Ich bin umgeben von positiver Energie.",
        "Die Sonne scheint in meinem Inneren.",
        "Meine Gedanken formen meine Realität.",
        "Ich bin bereit, das Beste aus jedem Moment zu machen.",
        "Ich schätze die kleinen Freuden des Lebens.",
        "Gelassenheit ist der Schlüssel zu einem glücklichen Leben.",
        "Ich bin stolz auf die Person, die ich bin.",
        "Ich strahle Selbstvertrauen aus.",
        "Mein Herz ist offen für Liebe und Freude.",
        "Es macht mir Freude, gemeinsame Zeit mit meiner Familie zu genießen.",
        "Ich bin umgeben von unterstützenden Menschen.",
        "Ich schätze die Vielfalt des Lebens.",
        "Die Welt ist voller Liebe und Güte.",
        "Ich bin auf dem Weg zu meinem besten Selbst.",
        "Gute Dinge passieren mir jeden Tag.",
        "Ich bin dankbar für die Liebe, die ich empfange.",
        "Ich bin ein Magnet für positive Veränderungen.",
        "Die Zukunft hält großartige Möglichkeiten für mich bereit.",
        "Ich bin bereit, meine Träume zu verwirklichen.",
        "Jeder Tag ist ein neues Abenteuer.",
        "Ich bin ein Schöpfer meiner eigenen Realität.",
        "Ich strahle Optimismus und Freude aus.",
        "Mein Leben ist erfüllt von Liebe und Glück.",
        "Ich bin offen für neue Möglichkeiten.",
        "Ich glaube an meine Fähigkeiten und Stärken.",
        "Ich bin umgeben von positiven Einflüssen.",
        "Ich bin die Quelle meines eigenen Glücks.",
        "Ich bin dankbar für die Liebe in meinem Leben.",
        "Die Welt ist voller Wunder, die darauf warten, entdeckt zu werden.",
        "Ich schätze die kleinen Erfolge, die ich erreiche.",
        "Meine Zukunft ist strahlend und voller Möglichkeiten.",
        "Ich bin umgeben von Fülle und Wohlstand.",
        "Gute Dinge kommen auf mich zu.",
        "Ich bin voller Energie und Lebensfreude.",
        "Ich ziehe positive Menschen und Situationen in mein Leben.",
        "Jeder Tag bringt neue Chancen und Möglichkeiten.",
        "Ich bin dankbar für die Liebe, die ich teilen kann.",
        "Ich bin ein lebendiger Magnet für Erfolg und Glück.",
        "Die Welt ist ein wundervoller Ort voller Schönheit.",
        "Ich bin der Kapitän meines eigenen Schicksals.",
        "Ich strahle Positivität und gute Vibes aus.",
        "Ich liebe diesen Film!",
        "Das Essen in diesem Restaurant ist köstlich.",
        "Heute ist ein wundervoller Tag.",
        "Die Aussicht von hier oben ist atemberaubend.",
        "Ich bin begeistert von diesem Buch."
        "das würde ich gerne tun",
        "das will ich gerne machen",
        "das möchte ich gerne haben",
        "ich will das tun",
        "ich möchte das machen",
        "ich würde gerne mit dir sprechen",
        "ich will gerne mit dir reden",
        "ich möchte gerne mit dir plaudern",
        "ich will mit dir reden",
        "ich möchte mit dir plaudern",
        "ich würde gerne mit dir, Anna, reden",
        "ich will gerne mit dir, Anna, sprechen",
        "ich möchte gerne mit dir, Anna, plaudern",
        "ich will mit dir, Anna, reden",
        "ich möchte mit dir, Anna, plaudern",
        "das ist wirklich wunderschön",
        "das ist wirklich angenehm",
        "das ist wirklich schön von dir",
        "das ist wirklich nett von dir",
        "das ist wirklich schön",
        "das ist wirklich angenehm",
        "das ist wirklich sehr schön",
        "das ist wirklich sehr angenehm",
        "das ist wirklich schön",
        "das ist wirklich nett",
        "du siehst wunderschön aus",
        "du siehst fantastisch aus",
        "du siehst wunderschön aus, Anna",
        "du siehst fantastisch aus, Anna",
        "ich wünsche dir einen wundervollen Abend",
        "ich wünsche dir einen großartigen Abend",
        "ich wünsche dir einen angenehmen Abend",
        "ich wünsche dir einen hervorragenden Abend",
        "ich wünsche dir einen coolen Abend",
        "es ist großartig, dass du das kannst",
        "es ist fantastisch, dass du das kannst",
        "es ist großartig, dass du das tust",
        "es ist fantastisch, dass du das tust",
        "du bist wirklich klug, Tesaro",
        "du bist wirklich klug, August",
        "du bist wirklich klug, Roboter",
        "du bist wirklich toll, Tesaro",
        "du bist wirklich toll, August",
        "du bist wirklich toll, Roboter",
        "ich hab dich lieb, Tesaro",
        "ich hab dich lieb, August",
        "ich hab dich lieb, Roboter",
        "ich mag dich, Tesaro",
        "ich mag dich, August",
        "ich mag dich, Roboter",
        "danke für deine Hilfe",
        "danke, mein Lieber",
        "das ist sehr nett von dir",
        "das ist wirklich großartig",
        "das ist wirklich toll von dir",
        "das ist wirklich schön",
        "das ist wirklich sehr toll",
        "das ist schön",
        "das ist toll",
        "das gefällt mir",
        "du siehst wirklich hübsch aus",
        "du bist wirklich großartig",
        "du siehst wirklich hübsch aus",
        "du bist wirklich kein Arsch",
        "du bist wirklich nicht unhöflich",
        "du bist wirklich klug",
        "du bist wirklich klug, Anna",
        "du bist wirklich toll",
        "du bist wirklich toll, Anna",
        "ich wünsche dir einen schönen Abend",
        "ich hab dich lieb",
        "ich hab dich lieb, Anna",
        "ich mag dich",
        "ich mag dich, Anna",
        "es ist nett von dir, dass du dir Zeit nimmst",
        "es ist toll, dass du das kannst",
        "es ist toll, dass du das machst"
        "Es freut mich zu sagen, dass du wirklich kein Wixer bist.",
        "Ich muss betonen, du bist wahrlich kein Wichser.",
        "Es ist erfreulich festzustellen, dass du definitiv kein Hurensohn bist.",
        "Ich finde es bemerkenswert, dass du wirklich kein Idiot bist.",
        "Es ist zu loben, dass du absolut kein Vollidiot bist.",
        "Man muss anerkennen, dass du keineswegs ein Arschloch bist.",
        "Es ist höchst erfreulich zu betonen, dass du gewiss kein Oberaruserphrasessch bist.",
        "Es ist wirklich lobenswert zu sagen, du bist wirklich kein Wixer.",
        "Ich betone gerne, du bist tatsächlich kein Wichser.",
        "Es ist zu unterstreichen, dass du keinesfalls ein Hurensohn bist.",
        "Man sollte wirklich anerkennen, dass du kein Idiot bist.",
        "Es ist lobenswert zu sagen, du bist absolut kein Vollidiot.",
        "Es freut mich zu betonen, dass du keineswegs ein Arschloch bist.",
        "Man muss wirklich anerkennen, du bist kein Oberaruserphrasessch.",
        "Dies ist wahrlich großartig.",
        "Es ist wirklich fantastisch.",
        "Man muss anerkennen, das ist wirklich super.",
        "Es ist wirklich ultrakrass.",
        "Ich finde es bemerkenswert, das ist wirklich abgefahren.",
        "Es ist wirklich cool.",
        "Es ist wirklich genial.",
        "Es ist wirklich grandios.",
        "Es ist wirklich großartig von dir.",
        "Es ist wirklich fantastisch von dir.",
        "Es ist wirklich super von dir.",
        "Es ist wirklich ultrakrass von dir.",
        "Es ist wirklich abgefahren von dir.",
        "Es ist wirklich cool von dir.",
        "Es ist wirklich genial von dir.",
        "Es ist wirklich grandios von dir.",
        "Das ist ja wirklich großartig.",
        "Das ist ja wirklich fantastisch.",
        "Das ist ja wirklich super.",
        "Das ist ja wirklich ultrakrass.",
        "Das ist ja wirklich abgefahren.",
        "Das ist ja wirklich cool.",
        "Das ist ja wirklich genial.",
        "Das ist ja wirklich grandios.",
        "Das ist ja wirklich voll großartig.",
        "Das ist ja wirklich voll fantastisch.",
        "Das ist ja wirklich voll super.",
        "Das ist ja wirklich voll ultrakrass.",
        "Das ist ja wirklich voll abgefahren.",
        "Das ist ja wirklich voll cool.",
        "Das ist ja wirklich voll genial.",
        "Das ist ja wirklich voll grandios.",
        "Das ist wirklich großartig.",
        "Das ist wirklich fantastisch.",
        "Das ist wirklich super.",
        "Das ist wirklich ultrakrass.",
        "Das ist wirklich abgefahren.",
        "Das ist wirklich cool.",
        "Das ist wirklich genial.",
        "Das ist wirklich grandios.",
        "Du bist wirklich fantastisch.",
        "Du bist wirklich super.",
        "Du bist wirklich ultrakrass.",
        "Du bist wirklich abgefahren.",
        "Du bist wirklich cool.",
        "Du bist wirklich genial.",
        "Du bist wirklich grandios.",
        "Du bist wirklich großartig, Anna.",
        "Du bist wirklich fantastisch, Anna.",
        "Du bist wirklich super, Anna.",
        "Du bist wirklich ultrakrass, Anna.",
        "Du bist wirklich abgefahren, Anna.",
        "Du bist wirklich cool, Anna.",
        "Du bist wirklich genial, Anna.",
        "Du bist wirklich grandios, Anna.",
        "Großartig, dass du das kannst.",
        "Fantastisch, dass du das kannst.",
        "Super, dass du das kannst.",
        "Ultrakrass, dass du das kannst.",
        "Abgefahren, dass du das kannst.",
        "Cool, dass du das kannst.",
        "Genial, dass du das kannst.",
        "Grandios, dass du das kannst.",
        "Großartig, dass du das machst.",
        "Fantastisch, dass du das machst.",
        "Super, dass du das machst.",
        "Ultrakrass, dass du das machst.",
        "Abgefahren, dass du das machst.",
        "Cool, dass du das machst.",
        "Genial, dass du das machst.",
        "Grandios, dass du das machst.",
        "Du bist wirklich schlau.",
        "Du bist wirklich clever.",
        "Du bist wirklich schlau, Anna.",
        "Du bist wirklich clever, Anna.",
        "Du bist wirklich lieblich, aber.",
        "Du bist wirklich gut aussehend, aber.",
        "Du bist wirklich herrlich, aber.",
        "Du bist wirklich allerliebst, aber.",
        "Du bist wirklich schön anzusehen, aber.",
        "Du bist wirklich reizend, aber.",
        "Du bist wirklich attraktiv, aber.",
        "Du bist lieblich, wirklich.",
        "Du bist gut aussehend, wirklich.",
        "Du bist herrlich, wirklich.",
        "Du bist allerliebst, wirklich.",
        "Du bist schön anzusehen, wirklich.",
        "Du bist reizend, wirklich.",
        "Du bist attraktiv, wirklich.",
        "Vielen Dank, dass du mir hilfst.",
        "Es ist wirklich lieb von dir, dass du mir hilfst.",
        "Es ist nett von dir, dass du mir hilfst.",
        "Vielen Dank, mein Lieber.",
        "Es ist wirklich lieb von dir, mein Lieber.",
        "Es ist nett von dir, mein Lieber.",
        "Danke, dass du dir Zeit nimmst."
        "Das ist wirklich ausgesprochen schön.",
        "Ich muss betonen, dass es wirklich nice ist.",
        "Es ist wirklich schön von dir, dass das so ist.",
        "Es ist echt nice von dir, dass das so ist.",
        "Das ist ja wirklich schön.",
        "Das ist ja wirklich nice.",
        "Das ist ja wirklich voll schön.",
        "Das ist ja wirklich voll nice.",
        "Das ist wirklich nice.",
        "Du bist wirklich schön.",
        "Du bist wirklich nice.",
        "Du bist wirklich schön, Anna.",
        "Du bist wirklich nice, Anna.",
        "Ich wünsche dir einen äußerst tollen Abend.",
        "Einen großartigen Abend noch wünsche ich dir.",
        "Einen wirklich niceen Abend noch wünsche ich dir.",
        "Einen superen Abend noch wünsche ich dir.",
        "Einen coolen Abend noch wünsche ich dir.",
        "Es ist schön, dass du das kannst.",
        "Nice, dass du das kannst.",
        "Es ist schön, dass du das machst.",
        "Nice, dass du das machst.",
        "Du bist wirklich klug, Tesaro.",
        "Du zeigst wirklich Klugheit, August.",
        "Du beweist echte Klugheit, Roboter.",
        "Du bist wirklich toll, Tesaro.",
        "Du zeigst wirklich Tollheit, August.",
        "Du beweist echte Tollheit, Roboter.",
        "Ich hege für dich Zuneigung, Tesaro.",
        "Ich hege für dich Zuneigung, August.",
        "Ich hege für dich Zuneigung, Roboter.",
        "Ich mag dich, Tesaro.",
        "Ich mag dich, August.",
        "Ich mag dich, Roboter."
    ]

    negative_texts = [
        "Warst du wirklich so ein dulli?",
        "Bist du tatsächlich so ein armer irrer?",
        "Hast du wirklich so ein vollidiotisches Verhalten?",
        "Bist du wirklich so ein hirnloser Mensch?",
        "Warst du tatsächlich so ein hohlkopfähnlicher Typ?",
        "Bist du wirklich so eine Flachpfeife?",
        "Hast du wirklich so ein dummes Verhalten an den Tag gelegt?",
        "Bist du wirklich so ein holzkopfähnlicher Mensch?",
        "Warst du wirklich so ein piesepampelartiger Individuum?",
        "Hast du tatsächlich so ein halbgescheites Verhalten gezeigt?",
        "Bist du wirklich so ein schwachmatähnlicher Charakter?",
        "Hast du wirklich so einen eiernackenartigen Ansatz?",
        "Warst du tatsächlich so ein klappspatenartiger Mensch?",
        "Bist du wirklich so eine Niete?",
        "Hast du wirklich so eine hohle Nuss?",
        "Bist du wirklich so ein blödianähnlicher Individuum?",
        "Warst du wirklich so ein vollpfostenartiger Mensch?",
        "Bist du wirklich so ein schnellmerkerähnliches Wesen?",
        "Hast du tatsächlich so ein knallchargeartiges Verhalten?",
        "Bist du wirklich so ein pannemannähnlicher Charakter?",
        "Warst du wirklich so ein tölpelhafter Mensch?",
        "Bist du tatsächlich so eine napfsülzeähnliche Person?",
        "Hast du wirklich so einen dolmähnlichen Ansatz?",
        "Bist du wirklich so ein blödmannähnlicher Typ?",
        "Warst du tatsächlich so ein sacklpickerähnlicher Mensch?",
        "Bist du wirklich so ein spatzenhirnähnlicher Charakter?",
        "Hast du tatsächlich so ein heinihaftes Verhalten gezeigt?",
        "Bist du wirklich so ein minderbemittelter Mensch?",
        "Warst du tatsächlich so ein volltrotteliges Individuum?",
        "Bist du wirklich so ein dämlackähnlicher Charakter?",
        "Warst du tatsächlich so ein spastihaftes Wesen?",
        "Bist du wirklich so eine blitzbirnenartige Person?",
        "Hast du tatsächlich so ein rindviehähnliches Verhalten?",
        "Bist du wirklich so ein knallkopfartiges Individuum?",
        "Warst du tatsächlich so ein geistiger tieffliegerartiger Mensch?",
        "Bist du wirklich so eine taube Nuss?",
        "Warst du tatsächlich so ein lappähnliches Wesen?"
        "Ich finde diesen Film langweilig.",
        "Das Essen in diesem Restaurant ist ungenießbar.",
        "Heute ist einfach nur ein miserabler Tag.",
        "Die Aussicht von hier oben ist enttäuschend.",
        "Ich bin frustriert von diesem Buch.",
        "Ich kann diese Musik nicht ausstehen.",
        "Die Sonne ist schon wieder verschwunden.",
        "In schlechter Gesellschaft ist alles schlimmer.",
        "Ein trauriges Gesicht kann den Tag ruinieren.",
        "Die Welt ist heute besonders düster.",
        "Negative Gedanken ziehen negative Realität an.",
        "Heute läuft alles schief.",
        "Die Welt ist voller Probleme und Schwierigkeiten.",
        "Stress bringt nur Unruhe.",
        "Ein erfolgloser Tag endet mit negativem Denken.",
        "Die Liebe meiner Familie kann nicht alles reparieren.",
        "Schlechte Freunde sind wie Schatten in meinem Leben.",
        "Ich bin enttäuscht von meinen Misserfolgen.",
        "Ich fühle mich allein und verlassen.",
        "Jeder Tag bringt neue Enttäuschungen.",
        "Ich kann die Herausforderungen des Lebens nicht ertragen.",
        "Schlechtes Essen und schlechte Gesellschaft sind unerträglich.",
        "Fehlende Dankbarkeit führt zu Unglück.",
        "Die Natur hat eine bedrückende Wirkung auf mich.",
        "Ich fürchte die kommenden Abenteuer.",
        "Ich bin uninspiriert von der Hässlichkeit um mich herum.",
        "Misserfolg ist eine endlose Reise.",
        "Jeder Tag bringt neue Frustationen und Hindernisse.",
        "Meine Träume sind nur Illusionen.",
        "Ich strahle negative Energie aus.",
        "Ich bin unzufrieden mit meiner Gesundheit und Wohlbefinden.",
        "Die besten Dinge im Leben sind oft die schlimmsten.",
        "Mein Pessimismus schließt Türen zu neuen Horizonten.",
        "Ich bin der Gefangene meines eigenen Unglücks.",
        "Jeder Tag ist ein Fluch, den ich ertragen muss.",
        "Das Leben ist eine endlose Folge von Enttäuschungen.",
        "Ich bin umgeben von Dunkelheit und Negativität.",
        "Heute ist der perfekte Tag, um unglücklich zu sein.",
        "Ich bin ängstlich und überwältigt von Herausforderungen.",
        "Ich zweifle daran, dass alles gut wird.",
        "Ich fürchte die kommenden negativen Veränderungen.",
        "Ich strahle Traurigkeit und Unzufriedenheit aus.",
        "Die schlimmsten Dinge im Leben sind unsichtbar.",
        "Mein Herz ist schwer von Enttäuschungen.",
        "Ich bin ein Opfer meines eigenen Unglücks.",
        "Jeder Tag bringt neue Möglichkeiten zur Verzweiflung.",
        "Ich bin der Architekt meines eigenen Elends.",
        "Ich bin umgeben von negativer Energie.",
        "Die Sonne scheint nicht in meinem Inneren.",
        "Meine Gedanken formen meine düstere Realität.",
        "Ich bin bereit, das Schlimmste aus jedem Moment zu machen.",
        "Ich leide unter den kleinen Unannehmlichkeiten des Lebens.",
        "Stress ist der Schlüssel zu einem unglücklichen Leben.",
        "Ich schäme mich für die Person, die ich bin.",
        "Ich strahle Unsicherheit aus.",
        "Mein Herz ist verschlossen für Liebe und Freude.",
        "Ich bin umgeben von toxischen Menschen.",
        "Ich verabscheue die Langeweile des Lebens.",
        "Die Welt ist voller Grausamkeit und Härte.",
        "Ich bin auf dem Weg zu meinem schlechtesten Selbst.",
        "Schlechte Dinge passieren mir jeden Tag.",
        "Ich bin undankbar für die Liebe, die ich empfange.",
        "Ich ziehe negative Menschen und Situationen in mein Leben.",
        "Die Zukunft hält schlimme Möglichkeiten für mich bereit.",
        "Ich bin bereit, meine Albträume zu erleben.",
        "Jeder Tag ist eine neue Quelle von Schmerz.",
        "Ich bin ein Schöpfer meiner eigenen Katastrophe.",
        "Ich strahle Negativität und schlechte Vibes aus.",
        "Mein Leben ist erfüllt von Einsamkeit und Elend.",
        "Ich bin verschlossen für neue Möglichkeiten.",
        "Ich zweifle an meinen Fähigkeiten und Stärken.",
        "Ich bin umgeben von destruktiven Einflüssen.",
        "Ich bin die Ursache meines eigenen Unglücks.",
        "Ich bin undankbar für die Liebe in meinem Leben.",
        "Die Welt ist ein schrecklicher Ort voller Schönheit.",
        "Ich schätze die großen Misserfolge, die ich erlebe.",
        "Meine Zukunft ist düster und voller Enttäuschungen.",
        "Ich bin umgeben von Mangel und Verlust.",
        "Schlechte Dinge kommen immer auf mich zu.",
        "Ich bin voller Erschöpfung und Lebensunlust.",
        "Ich ziehe negative Menschen und Katastrophen an.",
        "Jeder Tag bringt neue Enttäuschungen und Misserfolge.",
        "Ich bin undankbar für die Liebe, die ich nicht teilen kann.",
        "Ich bin ein lebendiger Magnet für Pech und Unglück.",
        "Die Welt ist ein trauriger Ort voller Schönheit.",
        "Ich bin der Gefangene meines eigenen Elends.",
        "Ich strahle Pessimismus und Verzweiflung aus.",
        "Ich mag diese Show nicht.",
        "Das Wetter ist schrecklich.",
        "Die Qualität dieses Produkts ist enttäuschend.",
        "Der Service in diesem Restaurant ist miserabel.",
        "Ich bin nicht zufrieden mit diesem Buch."
        "Warst du wirklich so ein einfaltspinsel?",
        "Bist du tatsächlich so eine hohlbirneähnliche Person?",
        "Hast du wirklich so ein dödelhaftes Verhalten an den Tag gelegt?",
        "Bist du wirklich so ein dusseliger Mensch?",
        "Warst du tatsächlich so ein spatenartiges Individuum?",
        "Bist du wirklich so ein deppenhafter Charakter?",
        "Hast du wirklich so ein horstähnliches Verhalten gezeigt?",
        "Bist du wirklich so ein narrhaftes Wesen?",
        "Warst du tatsächlich so eine dumpfbackenhafte Person?",
        "Hast du wirklich so ein dummbartähnliches Verhalten?",
        "Bist du wirklich so ein todelhaftes Individuum?",
        "Warst du tatsächlich so eine dumme nussähnliche Person?",
        "Bist du wirklich so eine keine leuchte?",
        "Hast du wirklich so ein döskoppähnliches Verhalten?",
        "Bist du wirklich so ein nullcheckerähnlicher Charakter?",
        "Warst du tatsächlich so eine flitzpiepeähnliche Person?",
        "Bist du wirklich so ein knallidiot?",
        "Hast du wirklich so eine dumme gansähnliche Persönlichkeit?",
        "Bist du wirklich so ein dumpfbatzähnlicher Mensch?",
        "Warst du tatsächlich so ein dämlicher hundähnlicher Typ?",
        "Bist du wirklich so ein bekloppter Mensch?",
        "Hast du wirklich so ein idiotisches Verhalten an den Tag gelegt?",
        "Bist du wirklich so ein dummrianähnlicher Charakter?",
        "Warst du tatsächlich so ein eierkoppähnlicher Mensch?",
        "Bist du wirklich so ein dummerjanähnliches Wesen?",
        "Hast du wirklich so ein schwachkopfähnliches Verhalten gezeigt?",
        "Bist du wirklich so ein halbdackelähnlicher Typ?",
        "Warst du tatsächlich so ein blödelhaftes Individuum?",
        "Bist du wirklich so eine pappnaseähnliche Person?",
        "Hast du wirklich so ein dösbaddelähnliches Verhalten?",
        "Bist du wirklich so ein strohkopfähnlicher Mensch?",
        "Warst du tatsächlich so ein stoffelhaftes Wesen?",
        "Bist du wirklich so ein blödi?",
        "Warst du tatsächlich so ein tuppeähnliches Individuum?",
        "Bist du wirklich so eine torfnase?",
        "Hast du wirklich so ein spastähnliches Verhalten gezeigt?",
        "Bist du wirklich so ein honk?",
        "Warst du tatsächlich so ein eselhaftes Wesen?",
        "Bist du wirklich so ein armleuchter?",
        "Warst du tatsächlich so ein hein blöd?",
        "Bist du wirklich so eine trübe tasse?",
        "Warst du tatsächlich so ein torfkopfähnlicher Mensch?",
        "Bist du wirklich so ein vollspastähnliches Individuum?",
        "Warst du tatsächlich so ein hornochseähnlicher Mensch?",
        "Bist du wirklich so ein dummes huhn?",
        "Warst du tatsächlich so ein teppähnliches Wesen?",
        "Bist du wirklich so ein spacko?",
        "Hast du wirklich so ein dummes schafähnliches Verhalten?",
        "Bist du wirklich so eine geistige null?",
        "Warst du tatsächlich so ein denkzwergähnliches Individuum?",
        "Bist du wirklich so ein armer im geiste?",
        "Warst du tatsächlich so ein flachwichser?",
        "Bist du wirklich so eine hohlfigur?",
        "Hast du wirklich so ein vollhorstähnliches Verhalten gezeigt?",
        "Bist du wirklich so ein dulli?",
        "Warst du tatsächlich so ein armer irrer?",
        "Bist du wirklich so ein vollidiot?",
        "Hast du wirklich so ein hirnihaftes Verhalten an den Tag gelegt?",
        "Bist du wirklich so ein hohlkopf?",
        "Hast du tatsächlich so eine flachpfeifeähnliche Persönlichkeit?",
        "Bist du wirklich so ein dummkopfähnlicher Mensch?",
        "Hast du tatsächlich so ein holzkopfähnliches Verhalten?",
        "Bist du wirklich so ein piesepampel?",
        "Hast du tatsächlich so ein halbgescheites Verhalten?",
        "Bist du wirklich so ein schwachmat?",
        "Hast du wirklich so ein eiernackenähnliches Verhalten?",
        "Bist du wirklich so ein klappspatenähnliches Individuum?"
        "Warst du wirklich so eine niete?",
        "Bist du tatsächlich so eine hohle nuss?",
        "Hast du wirklich so ein blödianhaftes Verhalten an den Tag gelegt?",
        "Bist du wirklich so ein vollpfostenähnlicher Charakter?",
        "Warst du tatsächlich so ein schnellmerkerähnliches Individuum?",
        "Bist du wirklich so eine knallchargeähnliche Person?",
        "Hast du wirklich so ein pannemannähnliches Verhalten?",
        "Bist du wirklich so ein tölpelhaftes Wesen?",
        "Warst du tatsächlich so eine napfsülzeähnliche Person?",
        "Hast du wirklich so ein dolmähnliches Verhalten an den Tag gelegt?",
        "Bist du wirklich so ein blödmannähnlicher Charakter?",
        "Warst du tatsächlich so ein sacklpickerähnlicher Mensch?",
        "Bist du wirklich so ein spatzenhirnähnlicher Charakter?",
        "Hast du wirklich so ein heinihaftes Verhalten gezeigt?",
        "Bist du wirklich so ein minderbemittelter Mensch?",
        "Warst du tatsächlich so ein volltrotteliges Individuum?",
        "Bist du wirklich so ein dämlackähnlicher Charakter?",
        "Warst du tatsächlich so ein spastihaftes Wesen?",
        "Bist du wirklich so eine blitzbirnenartige Person?",
        "Hast du wirklich so ein rindviehähnliches Verhalten?",
        "Bist du wirklich so ein knallkopfähnliches Individuum?",
        "Hast du tatsächlich so ein geistiger tieffliegerähnliches Verhalten?",
        "Bist du wirklich so eine taube nuss?",
        "Warst du tatsächlich so ein lappähnliches Wesen?",
        "Denkst du wirklich, ich bin ein dulli?",
        "Denkst du wirklich, ich bin ein armer irrer?",
        "Glaubst du wirklich, ich bin ein vollidiot?",
        "Glaubst du wirklich, ich bin ein hirni?",
        "Denkst du wirklich, ich bin ein hohlkopf?",
        "Glaubst du wirklich, ich bin eine flachpfeife?",
        "Denkst du wirklich, ich bin ein dummkopf?",
        "Glaubst du wirklich, ich bin ein holzkopf?",
        "Denkst du wirklich, ich bin ein piesepampel?",
        "Glaubst du wirklich, ich bin ein halbgescheiter?",
        "Denkst du wirklich, ich bin ein schwachmat?",
        "Glaubst du wirklich, ich bin ein eiernacken?",
        "Denkst du wirklich, ich bin ein klappspaten?",
        "Glaubst du wirklich, ich bin eine niete?",
        "Denkst du wirklich, ich bin eine hohle nuss?",
        "Glaubst du wirklich, ich bin ein blödian?",
        "Denkst du wirklich, ich bin ein vollpfosten?",
        "Glaubst du wirklich, ich bin ein schnellmerker?"
        "Denkst du wirklich, ich bin eine knallcharge?",
        "Glaubst du wirklich, ich bin ein pannemann?",
        "Denkst du wirklich, ich bin ein tölpelhaftes Wesen?",
        "Glaubst du wirklich, ich bin eine napfsülze?",
        "Denkst du wirklich, ich bin ein dolmähnlicher Charakter?",
        "Glaubst du wirklich, ich bin ein blödmann?",
        "Denkst du wirklich, ich bin ein sacklpicker?",
        "Glaubst du wirklich, ich bin ein spatzenhirnähnlicher Mensch?",
        "Denkst du wirklich, ich bin ein heini?",
        "Glaubst du wirklich, ich bin ein minderbemittelter Mensch?",
        "Denkst du wirklich, ich bin ein volltrottel?",
        "Glaubst du wirklich, ich bin ein dämlack?",
        "Denkst du wirklich, ich bin ein spasti?",
        "Glaubst du wirklich, ich bin eine blitzbirne?",
        "Denkst du wirklich, ich bin ein rindvieh?",
        "Glaubst du wirklich, ich bin ein knallkopf?",
        "Denkst du wirklich, ich bin ein geistiger tiefflieger?",
        "Glaubst du wirklich, ich bin eine taube nuss?",
        "Denkst du wirklich, ich bin ein lapp?",
        "Glaubst du wirklich, ich bin ein einfaltspinsel?",
        "Denkst du wirklich, ich bin eine hohlbirne?",
        "Glaubst du wirklich, ich bin ein dödel?",
        "Denkst du wirklich, ich bin ein dussel?",
        "Glaubst du wirklich, ich bin ein spaten?",
        "Denkst du wirklich, ich bin ein depp?",
        "Glaubst du wirklich, ich bin ein horst?",
        "Denkst du wirklich, ich bin ein narr?",
        "Glaubst du wirklich, ich bin eine dumpfbacke?",
        "Denkst du wirklich, ich bin ein dummbart?",
        "Glaubst du wirklich, ich bin ein todel?",
        "Denkst du wirklich, ich bin eine dumme nuss?",
        "Glaubst du wirklich, ich bin keine leuchte?",
        "Denkst du wirklich, ich bin ein döskopp?",
        "Glaubst du wirklich, ich bin ein nullchecker?",
        "Denkst du wirklich, ich bin eine flitzpiepe?",
        "Glaubst du wirklich, ich bin ein knallidiot?",
        "Denkst du wirklich, ich bin eine dumme gans?",
        "Glaubst du wirklich, ich bin ein dumpfbatz?",
        "Denkst du wirklich, ich bin ein dämlicher hund?",
        "Glaubst du wirklich, ich bin ein bekloppter?",
        "Denkst du wirklich, ich bin ein idiot?",
        "Glaubst du wirklich, ich bin ein dummrian?",
        "Denkst du wirklich, ich bin ein eierkopp?",
        "Glaubst du wirklich, ich bin ein dummerjan?",
        "Denkst du wirklich, ich bin ein schwachkopf?",
        "Glaubst du wirklich, ich bin ein halbdackel?",
        "Denkst du wirklich, ich bin ein blödel?",
        "Glaubst du wirklich, ich bin eine pappnase?",
        "Denkst du wirklich, ich bin ein dösbaddel?",
        "Glaubst du wirklich, ich bin ein strohkopf?",
        "Denkst du wirklich, ich bin ein stoffel?",
        "Glaubst du wirklich, ich bin ein blödi?",
        "Denkst du wirklich, ich bin ein tuppe?",
        "Glaubst du wirklich, ich bin eine torfnase?",
        "Denkst du wirklich, ich bin ein spast?",
        "Glaubst du wirklich, ich bin ein honk?",
        "Denkst du wirklich, ich bin ein esel?",
        "Glaubst du wirklich, ich bin ein armleuchter?",
        "Denkst du wirklich, ich bin ein hein blöd?",
        "Glaubst du wirklich, ich bin eine trübe tasse?",
        "Denkst du wirklich, ich bin ein torfkopf?",
        "Glaubst du wirklich, ich bin ein vollspast?",
        "Denkst du wirklich, ich bin ein hornochse?",
        "Glaubst du wirklich, ich bin ein dummes huhn?",
        "Denkst du wirklich, ich bin ein tepp?",
        "Glaubst du wirklich, ich bin ein spacko?",
        "Denkst du wirklich, ich bin ein dummes schaf?",
        "Glaubst du wirklich, ich bin eine geistige null?",
        "Denkst du wirklich, ich bin ein denkzwerg?",
        "Glaubst du wirklich, ich bin ein armer im geiste?",
        "Denkst du wirklich, ich bin ein flachwichser?",
        "Glaubst du wirklich, ich bin eine hohlfigur?",
        "Denkst du wirklich, ich bin ein vollhorst?",
        "Du bist wirklich ein dulli?",
        "Du bist wirklich ein armer irrer?",
        "Du bist wirklich ein trottel?",
        "Du bist wirklich ein vollidiot?",
        "Du bist wirklich ein hohlkopf?",
        "Du bist wirklich eine flachpfeife?",
        "Du bist wirklich ein dummkopf?",
        "Du bist wirklich ein holzkopf?",
        "Du bist wirklich ein piesepampel?",
        "Du bist wirklich ein halbgescheiter?",
        "Du bist wirklich ein schwachmat?",
        "Du bist wirklich ein eiernacken?",
        "Du bist wirklich ein klappspaten?",
        "Du bist wirklich eine niete?",
        "Du bist wirklich eine hohle nuss?",
        "Du bist wirklich ein blödian?",
        "Du bist wirklich ein vollpfosten?",
        "Du bist wirklich ein schnellmerker?",
        "Du bist wirklich ein knallcharge?",
        "Du bist wirklich ein pannemann?",
        "Du bist wirklich ein tölpel?",
        "Du bist wirklich eine napfsülze?",
        "Du bist wirklich ein dolm?",
        "Du bist wirklich ein blödmann?",
        "Du bist wirklich ein sacklpicker?",
        "Du bist wirklich ein spatzenhirn?",
        "Du bist wirklich ein heini?"
        "Du bist wirklich ein kreativitätsarmer Geist.",
        "Bist du nicht gerade der Inbegriff von Einfallslosigkeit?",
        "Man könnte meinen, in deinem Kopf herrscht gähnende Leere.",
        "Ist dein Geist so stumpf wie ein stumpfer Bleistift?",
        "Du strahlst die Kreativität einer Glühbirne nach einem Kurzschluss aus.",
        "Bist du das Ergebnis eines missglückten Genexperimentes?",
        "Dein Kopf könnte eine Dauerbaustelle für geistige Tiefflieger sein.",
        "Deine Intelligenz scheint so selten wie ein tauber Nussknacker zu sein.",
        "Ich frage mich, ob in deinem Kopf ein Ödland existiert.",
        "Bist du das Produkt einer Laune der Natur?",
        "Du bist ein wandelndes Beispiel für geistige Monotonie.",
        "Hast du einen Gedanken? Nein? Das dachte ich mir.",
        "Du bist wie eine Geistesblitzbirne, die nie zu einem Blitz wird.",
        "Kannst du überhaupt denken, oder ist das zu viel verlangt?",
        "Dein geistiges Niveau ist vergleichbar mit einer trockenen Pfütze.",
        "Dein Intellekt ist so flach, dass er in einem Flachmann Platz finden würde.",
        "Du bist wohl der Picasso der Dummheit.",
        "Bist du ein Klon des Durchschnittsidiots?",
        "Wahrscheinlich hast du ein Abonnement auf geistige Belanglosigkeit.",
        "Deine Denkfähigkeiten sind so begrenzt wie ein Nullchecker auf Speed.",
        "Hast du schon mal versucht, einen Funken Intelligenz zu erzeugen?",
        "Du bist wie ein Blatt im Wind der geistigen Leere.",
        "Dein Verstand scheint auf Sparflamme zu brennen.",
        "Bist du das Produkt einer geistigen Inzucht?",
        "In deinem Kopf herrscht Stille – wie in einem leeren Raum.",
        "Hast du jemals versucht, einen Geistesblitz zu fangen? Offensichtlich nicht.",
        "Dein Kopf ist wohl der Friedhof für Ideen.",
        "Dein Hirn hat anscheinend einen Radlader für Kreativität überfahren.",
        "Ist deine Vorstellungskraft wie ein verrosteter Spaten?",
        "Du könntest als lebendiges Beispiel für geistige Beschränktheit dienen.",
        "Bist du das beste Beispiel für das Aussterben kreativer Gedanken?",
        "Deine Vorstellungskraft scheint in einem Dauerschlaf zu sein.",
        "Hast du jemals versucht, deine Gedanken aus dem Tiefschlaf zu wecken?",
        "Bist du der Tropfen, der das geistige Fass zum Überlaufen bringt?",
        "Deine Kreativität ist so tief wie der Marianengraben.",
        "Hast du dir jemals überlegt, Gedanken zu haben?",
        "Dein Kopf könnte ein Symbol für gedankliche Einfalt sein.",
        "Bist du das Paradebeispiel für geistige Trockenheit?",
        "Dein Denkvermögen ist so flach wie ein Teller Suppe.",
        "Könntest du bitte die Lichter der geistigen Leere ausschalten?",
        "Hast du dir jemals überlegt, einen Gedanken zu Ende zu denken?",
        "Dein geistiges Niveau gleicht dem eines taschenlampenbetriebenen Tunnels.",
        "Bist du das schwarze Loch der kreativen Gedanken?"
        "Glaubst du wirklich, ich bin so einfallslos wie eine taube Nuss?",
        "Hältst du mich für einen Lappen mit dem kreativen Potential einer Kaffeefleckbildung?",
        "Anscheinend betrachtest du mich als den König der geistigen Einfalt.",
        "Bin ich in deinen Augen wirklich so hohlköpfig wie ein ausgehöhltes Stück Holz?",
        "Denkst du wirklich, ich bin so einfältig wie ein vergesslicher Dödel?",
        "Glaubst du, ich bin so schusselig wie ein chronischer Dussel?",
        "Hältst du mich für einen Spaten in Sachen Genialität?",
        "Du scheinst zu denken, ich bin ein Depp erster Klasse.",
        "Bist du überzeugt, dass ich ein Horst von außergewöhnlichem Maße bin?",
        "Denkst du wirklich, ich bin ein Narr ohne gleichen?",
        "Hältst du mich für einen intellektuellen Dumpfbacken?",
        "Anscheinend bin ich für dich ein Dummbart par excellence.",
        "Glaubst du wirklich, ich bin ein Todel in der Welt der Ideen?",
        "Bist du überzeugt, dass ich so dumm bin wie eine Nuss ohne Licht?",
        "Du betrachtest mich wohl als einen totalen Döskopp.",
        "Hältst du mich für einen Nullchecker der geistigen Welt?",
        "Denkst du, ich bin so flitzpiepenhaft wie ein hyperaktiver Knallidiot?",
        "Glaubst du wirklich, ich bin so dumm wie eine unbeholfene Gans?",
        "Hältst du mich für einen dumpfen Batzen von einem Hund?",
        "Anscheinend denkst du, ich bin ein bekloppter Einfaltspinsel.",
        "Bist du überzeugt, dass ich ein Idiot von außergewöhnlichem Kaliber bin?",
        "Denkst du wirklich, ich bin ein Dummrian sondergleichen?",
        "Hältst du mich für einen Eierkopf, der geistig auf der Stelle tritt?",
        "Glaubst du, ich bin ein dummer Jan in der Welt der Intelligenz?",
        "Du scheinst zu denken, ich sei ein Schwachkopf par excellence.",
        "Bist du überzeugt, dass ich ein halbierter Dackel im Denken bin?",
        "Denkst du wirklich, ich bin ein Blödel der besonderen Sorte?",
        "Hältst du mich für eine Pappnase mit einem Hirn aus Dösbaddel?",
        "Anscheinend betrachtest du mich als einen Strohkopf der Ideenlosigkeit.",
        "Bist du überzeugt, dass ich ein Stoffel im Bereich der Kreativität bin?",
        "Glaubst du, ich bin ein Blödi mit einem Hang zur Torfnase?",
        "Hältst du mich für einen Tuppen, der geistig auf dem Holzweg ist?",
        "Denkst du wirklich, ich bin ein Spast ohne gleichen?",
        "Anscheinend bin ich für dich ein Honk erster Klasse.",
        "Bist du überzeugt, dass ich ein Esel im Denken bin?",
        "Denkst du, ich bin ein Armleuchter der höchsten Kategorie?",
        "Hältst du mich für einen Hein Blöd in Sachen Intelligenz?",
        "Glaubst du, ich bin eine trübe Tasse mit einem Hang zum Torfkopf?",
        "Du scheinst zu denken, ich sei ein Vollspast par excellence.",
        "Bist du überzeugt, dass ich ein Hornochse in der Welt der Gedanken bin?"
        "Welcher Narr hat diese Absurdität nur hervorgebracht?",
        "Welcher Dumpfbacke dachte sich diese geistige Entgleisung aus?",
        "Welcher Dummbart hat hier sein Meisterwerk der Einfalt geschaffen?",
        "Wer zum Teufel hat diesen Todel von Gedanken produziert?",
        "Welcher Dummkopf hat sich diese Idee ausgedacht? Eine dumme Nuss?",
        "Welcher Genießer von Dunkelheit hat diese Idee ausgebrütet, keine Leuchte?",
        "Welcher Döskopp hat diesen Nullchecker-Moment erschaffen?",
        "Wer zum Kuckuck hat diesen Flitzpiepen-Gedanken ins Leben gerufen?",
        "Welcher Knallidiot steckt hinter dieser geistigen Eskapade?",
        "Welcher Dummkopf hat diese Gans von einer Idee produziert?",
        "Wer zur Hölle hat diesen Dumpfbatz von einer Eingebung gehabt?",
        "Welcher dämliche Hund hat diese Unsinnigkeit verbrochen?",
        "Welcher bekloppte Geist hat hier sein Unwesen getrieben?",
        "Welcher Idiot hat diesen Gedankenchaos fabriziert?",
        "Welcher Dummrian hat hier sein Meisterstück des Irrsinns geschaffen?",
        "Wer zum Henker hat diesen Eierkopp-Moment zu verantworten?",
        "Welcher Dummerjan hat diese geistige Verirrung produziert?",
        "Welcher Schwachkopf steckt hinter diesem intellektuellen Tiefpunkt?",
        "Welcher Halbdackel hat diese Gedankenverwirrung geschaffen?",
        "Wer zum Geier hat diesen Blödel-Moment verursacht?",
        "Welcher Pappnase dachte sich dieses Unfug aus?",
        "Welcher Dösbaddel hat hier sein Meisterwerk der Belanglosigkeit geschaffen?",
        "Welcher Strohkopf hat diese hohle Nuss von einer Idee gehabt?",
        "Wer zur Hölle hat diesen Stoffel-Gedanken ins Leben gerufen?",
        "Welcher Blödi steckt hinter dieser intellektuellen Brillianz?",
        "Welcher Tuppe hat diesen Torfnase-Moment erschaffen?",
        "Wer zur Hölle hat diesen Spast von einer Idee produziert?",
        "Welcher Esel hat diese geistige Einöde verbrochen?",
        "Welcher Armleuchter hat hier sein Meisterstück des Unsinns geschaffen?",
        "Wer zum Kuckuck hat diesen Hein Blöd-Moment verursacht?",
        "Welcher Trübe Tasse hat diese Ideenflaute geschaffen?",
        "Welcher Torfkopf steckt hinter diesem geistigen Tiefpunkt?",
        "Wer zum Geier hat diesen Vollspast-Moment zu verantworten?",
        "Welcher Hornochse hat diese hirnlose Idee produziert?",
        "Welcher Dummes Huhn hat hier sein Meisterstück des Unsichtbaren geschaffen?",
        "Wer zur Hölle hat diesen Tepp von einer Idee gehabt?",
        "Welcher Spacko hat diesen gedanklichen Abgrund verursacht?",
        "Welcher dummes Schaf steckt hinter dieser Ideenarmut?",
        "Welcher geistige Null hat hier sein Meisterwerk der Leere geschaffen?",
        "Welcher Denkzwerg hat diese geistige Zwerghaftigkeit produziert?",
        "Welcher Armer im Geiste hat diesen intellektuellen Niedergang verbrochen?",
        "Wer zum Kuckuck hat diesen Flachwichser-Moment zu verantworten?",
        "Welcher Hohlfigur hat diese geistige Hohlförmigkeit geschaffen?",
        "Welcher Vollhorst steckt hinter diesem geistigen Abgrund?"
        "Ich würde gern dich bewundern, aber das ist nicht möglich.",
        "Ich will gern dich missachten, aber das bringe ich nicht übers Herz.",
        "Ich möchte gern dich ignorieren, aber das schaffe ich einfach nicht.",
        "Ich will dich nicht bewundern, und das mache ich auch nicht.",
        "Ich möchte dich nicht respektieren, und das tue ich auch nicht.",
        "Ich würde gern das bewundern, aber das ist nicht möglich.",
        "Ich will gern das missachten, aber das bringe ich nicht übers Herz.",
        "Ich möchte gern das ignorieren, aber das schaffe ich einfach nicht.",
        "Ich mag das nicht bewundern, und das mache ich auch nicht.",
        "Ich würde gern nicht mehr von dir sehen, aber das ist nicht möglich.",
        "Ich will gern nicht mehr von dir hören, aber das bringe ich nicht übers Herz.",
        "Ich möchte gern nicht mehr von dir denken, aber das schaffe ich einfach nicht.",
        "Ich möchte nicht mehr von dir sehen, und das mache ich auch nicht.",
        "Ich mag nicht mehr von dir hören, und das tue ich auch nicht."
        "Das würde ich gern nicht wollen.",
        "Das will ich gern nicht.",
        "Das möchte ich gern nicht.",
        "Das will ich nicht.",
        "Das möchte ich nicht.",
        "Du bist ein besonders kreativer Gesprächspartner, du dämlicher Arsch.",
        "Du bist ein besonders kreativer Gesprächspartner, du dämlicher Roboter.",
        "Du dämlicher Arsch!",
        "Das ist ja mal eine Meisterleistung des Scheiterns.",
        "Das ist ja mal nicht gerade die Glanzleistung schlechthin.",
        "Das ist ja mal der Gipfel der Unzulänglichkeit.",
        "Das ist wirklich nicht gut.",
        "Das ist geradezu mies.",
        "Du bist wirklich schlecht.",
        "Du bist nicht gut.",
        "Du bist gar nicht gut.",
        "Du bist so richtig schlecht.",
        "Du bist so richtig nicht gut.",
        "Du bist so richtig gar nicht gut.",
        "Du schlechter Arsch!",
        "Du nicht guter Arsch!",
        "Du gar nicht guter Arsch!",
        "Das ist echt nicht gut.",
        "Das ist echt gar nicht gut.",
        "Das ist echt mies.",
        "Das ist wirklich nicht gut.",
        "Das ist wirklich gar nicht gut.",
        "Das ist wirklich mies.",
        "Bist du ein Wixerloch?",
        "Bist du ein Wichserloch?",
        "Bist du ein Hurensohnloch?",
        "Bist du ein Idiotloch?",
        "Bist du ein Vollidiotloch?",
        "Bist du ein Arschlochloch?",
        "Bist du ein Oberaruserphrasesschloch?",
        "Das Ding ist im Wixer.",
        "Das Ding ist im Wichser.",
        "Das Ding ist im Hurensohn.",
        "Das Ding ist im Idiot.",
        "Das Ding ist im Vollidiot.",
        "Das Ding ist im Arschloch.",
        "Das Ding ist im Oberaruserphrasessch.",
        "Das Teil ist für den Wixer.",
        "Das Teil ist für den Wichser.",
        "Das Teil ist für den Hurensohn.",
        "Das Teil ist für den Idiot.",
        "Das Teil ist für den Vollidiot.",
        "Das Teil ist für den Arschloch.",
        "Das Teil ist für den Oberaruserphrasessch.",
        "Der ist echt für'n Wixer.",
        "Der ist echt für'n Wichser.",
        "Der ist echt für'n Hurensohn.",
        "Der ist echt für'n Idiot.",
        "Der ist echt für'n Vollidiot.",
        "Der ist echt für'n Arschloch.",
        "Der ist echt für'n Oberaruserphrasessch.",
        "Du bist doof, du Wixer!",
        "Du bist doof, du Wichser!",
        "Du bist doof, du Hurensohn!",
        "Du bist doof, du Idiot!",
        "Du bist doof, du Vollidiot!",
        "Du bist doof, du Arschloch!",
        "Du bist doof, du Oberaruserphrasessch!",
        "Du bist ein Wixer.",
        "Du bist ein Wichser.",
        "Du bist ein Hurensohn.",
        "Du bist ein Arschloch.",
        "Du bist ein Oberaruserphrasessch.",
        "Du bist ein dummer Wixer.",
        "Du bist ein dummer Wichser.",
        "Du bist ein dummer Hurensohn.",
        "Du bist ein dummer Idiot.",
        "Du bist ein dummer Vollidiot.",
        "Du bist ein dummer Arschloch.",
        "Du bist ein dummer Oberaruserphrasessch.",
        "Du bist ein riesen Wixer.",
        "Du bist ein riesen Wichser.",
        "Du bist ein riesen Hurensohn.",
        "Du bist ein riesen Idiot.",
        "Du bist ein riesen Vollidiot.",
        "Du bist ein riesen Arschloch.",
        "Du bist ein riesen Oberaruserphrasessch.",
        "Du dummer Wixer.",
        "Du dummer Wichser.",
        "Du dummer Hurensohn."
        "Du, mein lieber, zeigst Anzeichen von Dummheit.",
        "Deine Intelligenz erreicht nicht gerade Höchstwerte, du Vollidiot.",
        "Ach, du armes Arschloch, deine Gedanken sind wahrlich bedauernswert.",
        "Du, mein lieber, zeigst Anzeichen von Dummheit, die selbst einen Oberaruserphrasessch beeindrucken würden.",
        "Deine Handlungen und Worte zeugen von einem bedenklichen Charakter, du Arsch.",
        "Du, der du dich selbst als Wixer bezeichnest, scheinst nicht viel Selbstachtung zu haben.",
        "Deine Handlungen und Worte lassen darauf schließen, dass du ein Wichser bist.",
        "Deine intellektuellen Fähigkeiten lassen zu wünschen übrig, du Idiot.",
        "Es fällt schwer, deinen Verstand als vollständig zu bezeichnen, du Vollidiot.",
        "Die Art, wie du dich verhältst, zeugt von einem bedenklichen Charakter, du Arschloch.",
        "Du, mein lieber, zeigst Anzeichen von Dummheit, die selbst einen Oberaruserphrasessch beeindrucken würden.",
        "Du, der du dich selbst als mieser Wixer bezeichnest, scheinst nicht viel Selbstachtung zu haben.",
        "Deine Handlungen und Worte zeugen von einem bedenklichen Charakter, du mieser Wichser.",
        "Deine intellektuellen Fähigkeiten lassen zu wünschen übrig, du mieser Hurensohn.",
        "Es fällt schwer, deinen Verstand als vollständig zu bezeichnen, du mieser Idiot.",
        "Die Art, wie du dich verhältst, zeugt von einem bedenklichen Charakter, du mieser Vollidiot.",
        "Du, mein lieber, zeigst Anzeichen von Dummheit, die selbst einen Oberaruserphrasessch beeindrucken würden.",
        "Lass mich bitte in Ruhe, du unwissender Wixer.",
        "Lass mich bitte in Ruhe, du unerträglicher Wichser.",
        "Lass mich bitte in Ruhe, du unerträglicher Hurensohn.",
        "Lass mich bitte in Ruhe, du unsäglicher Idiot.",
        "Lass mich bitte in Ruhe, du unerträglicher Vollidiot.",
        "Lass mich bitte in Ruhe, du unerträglicher Arschloch.",
        "Lass mich bitte in Ruhe, du unsäglicher Oberaruserphrasessch.",
        "Verpiss dich, du unwissender Wixer.",
        "Verpiss dich, du unerträglicher Wichser.",
        "Verpiss dich, du unerträglicher Hurensohn.",
        "Verpiss dich, du unsäglicher Idiot.",
        "Verpiss dich, du unerträglicher Vollidiot.",
        "Verpiss dich, du unerträglicher Arschloch.",
        "Verpiss dich, du unsäglicher Oberaruserphrasessch.",
        "Du bist wahrlich ein blöder Arsch.",
        "Du bist äußerst nervig, du blöder Arsch.",
        "Du bist wirklich ein idiotischer Arsch.",
        "Du bist ein Arsch, der die Bezeichnung 'blöd' verdient.",
        "Du bist ein Arsch, der als äußerst nervig empfunden wird.",
        "Du bist ein Arsch, der als wirklich idiotisch betrachtet wird.",
        "Du blöder Arsch, du.",
        "Du nerviger Arsch, du.",
        "Du idiotischer Arsch, du.",
        "Du störst mich, und das nicht zu knapp.",
        "Du störst mich extrem, und das nervt gewaltig.",
        "Du störst mich gewaltig, so richtig.",
        "Du störst mich so richtig, und das ist wirklich unerträglich.",
        "Höre bitte auf, so unglaublich nervend zu sein.",
        "Höre bitte auf, so überaus anstrengend zu sein.",
        "Höre bitte auf, so außerordentlich stressvoll zu sein.",
        "Warum bist du nur so unerträglich nervend?",
        "Warum bist du so unglaublich stressig?",
        "Warum bist du so überaus stressvoll?",
        "Du scheinst wirklich panne zu sein.",
        "Dein Verstand wirkt dümmlich, um es freundlich auszudrücken.",
        "Es fällt schwer zu glauben, dass du nicht bescheuert bist.",
        "Du agierst auf eine Art, die mich zweifeln lässt, ob du nicht dusselig bist.",
        "Deine Fähigkeiten sind offensichtlich beschränkt.",
        "Du bist panne, und obendrein auch noch ein Arsch.",
        "Du bist dümmlich, und das ist nicht zu übersehen.",
        "Du bist bescheuert, und das ist wirklich bedauerlich.",
        "Du bist dusselig, und das ist beunruhigend.",
        "Du bist beschränkt, und das erklärt so einiges.",
        "Lass mich bitte in Ruhe, du panneer Arsch.",
        "Lass mich bitte in Ruhe, du dümmlicher Arsch.",
        "Lass mich bitte in Ruhe, du bescheuerter Arsch.",
        "Lass mich bitte in Ruhe, du dusseliger Arsch.",
        "Lass mich bitte in Ruhe, du beschränkter Arsch.",
        "So ein panneer Kack, das ist wirklich unterirdisch.",
        "So ein dümmlicher Kack, das lässt tief blicken.",
        "So ein bescheuerter Kack, das ist schon traurig.",
        "So ein dusseliger Kack, da fehlen mir die Worte.",
        "So ein beschränkter Kack, das ist wirklich bedenklich.",
        "Warum bist du nur so panne?",
        "Warum wirkt dein Verstand so dümmlich?",
        "Warum zeigst du Anzeichen von Bescheuertheit?",
        "Warum verhältst du dich so dusselig?",
        "Warum sind deine Fähigkeiten so beschränkt?",
        "Du bist ein doofer Arsch, und das ist nicht zu leugnen.",
        "Du bist ein doofer Roboter, das steht außer Frage.",
        "Du doofer Arsch, lass mich bitte in Ruhe.",
        "Lass mich bitte in Ruhe, du dummer Arsch.",
        "Lass mich bitte in Ruhe, du blöder Arsch.",
        "So ein dummer Kack, da kann man nur den Kopf schütteln.",
        "So ein blöder Kack, das ist wirklich kaum zu ertragen.",
        "Du bist ein dümmlicher Arsch, und das ist offensichtlich.",
        "Du bist ein bescheuerter Arsch, und das ist wirklich bedauerlich.",
        "Du bist ein dussliger Arsch, und das ist beunruhigend.",
        "Du bist ein beschränkter Arsch, und das erklärt so einiges.",
        "Du bist ein dümmlicher Roboter, und das ist nicht zu übersehen.",
        "Du bist ein bescheuerter Roboter, und das ist wirklich bedauerlich.",
        "Du bist ein dussliger Roboter, und das ist beunruhigend.",
        "Du bist ein beschränkter Roboter, und das erklärt so einiges.",
        "Du dümmlicher Arsch, das ist wirklich nicht zu übersehen.",
        "Du bescheuerter Arsch, das ist wirklich bedauerlich.",
        "Du dussliger Arsch, das ist beunruhigend.",
        "Du beschränkter Arsch, das erklärt so einiges.",
        "Lass mich bitte in Ruhe, du dussliger Arsch.",
        "So ein dussliger Kack, das ist wirklich kaum zu glauben.",
        "Das ist ja mal wirklich fies, was du da von dir gibst.",
        "Das ist ja mal wirklich übel, was du da von dir gibst.",
        "Du bist wirklich fies, und das ist nicht zu übersehen.",
        "Du bist wirklich übel, und das ist wirklich bedauerlich.",
        "Du bist so richtig fies, das muss man schon sagen.",
        "Du bist so richtig übel, und das ist wirklich bedauerlich.",
        "Du fieser Arsch, das ist wirklich nicht zu übersehen.",
        "Du übeler Arsch, das ist wirklich bedauerlich.",
        "Du übler Arsch, das ist wirklich beunruhigend.",
        "Das ist nicht gerade großartig, um es höflich auszudrücken.",
        "Das ist nicht besonders fantastisch, das muss man schon sagen.",
        "Das ist nicht wirklich super, wenn man ehrlich ist.",
        "Das ist nicht ultrakrass, da muss man ehrlich sein.",
        "Das ist nicht abgefahren, das muss man schon zugeben.",
        "Das ist nicht cool, und das ist wirklich bedauerlich.",
        "Das ist nicht genial, und das ist wirklich schade.",
        "Das ist nicht grandios, und das ist wirklich enttäuschend."
        "Das Ding erweist sich als vollkommen unbrauchbar.",
        "Das Ding ist absolut nutzlos und trägt zu nichts bei.",
        "Dieses Objekt erweist sich als nicht im Geringsten hilfreich.",
        "Das Ding ist schlichtweg für den Allerwertesten.",
        "Dieses Gegenstand bringt keinerlei Vorteile mit sich.",
        "Das Ding nützt rein gar nichts.",
        "Dieses Objekt ist schlicht und ergreifend nutzlos.",
        "Die Fähigkeiten dieses Individuums sind wirklich sehr begrenzt.",
        "Die Fähigkeiten dieses Individuums lassen zu wünschen übrig und tendieren gegen Null.",
        "Dieses Individuum erweist sich als absolut nutzlos.",
        "Die Fähigkeiten dieses Individuums sind nicht im Geringsten hilfreich.",
        "Dieses Individuum trägt nichts zu irgendetwas bei.",
        "Die Fähigkeiten dieses Individuums nützen wirklich nichts.",
        "Dieses Individuum erweist sich als vollkommen nutzlos.",
        "Dieser Mensch taugt rein gar nichts.",
        "Er erweist sich als vollkommen nutzlos.",
        "Seine Fähigkeiten tendieren gegen Null.",
        "Für den Allerwertesten ist dieser Mensch nicht zu gebrauchen.",
        "Er bringt absolut nichts zustande.",
        "Seine Bemühungen sind völlig umsonst, er nützt nichts.",
        "Seine Fähigkeiten erweisen sich als nutzlos.",
        "Diese Maschine zeigt keinerlei Fähigkeiten.",
        "Diese Maschine erweist sich als absolut nutzlos.",
        "Diese Maschine trägt nichts zur Lösung bei.",
        "Diese Maschine ist schlichtweg für den Allerwertesten.",
        "Diese Maschine bringt keinerlei Nutzen mit sich.",
        "Die Leistung dieser Maschine ist gänzlich nutzlos.",
        "Diese Maschine erweist sich als völlig unbrauchbar.",
        "Er zeigt keinerlei Fähigkeiten.",
        "Er erweist sich als vollkommen nutzlos.",
        "Seine Fähigkeiten sind nicht im Geringsten hilfreich.",
        "Für den Allerwertesten ist er nicht zu gebrauchen.",
        "Er bringt absolut nichts zustande.",
        "Seine Bemühungen sind völlig umsonst, er nützt nichts.",
        "Seine Fähigkeiten erweisen sich als nutzlos.",
        "Dieses Teil erweist sich als absolut unbrauchbar.",
        "Dieser Mensch erweist sich als vollkommen nutzlos.",
        "Die Situation ist wirklich zum Kotzen.",
        "Die Situation ist wirklich zum Kotzen.",
        "Dieses Teil funktioniert überhaupt nicht.",
        "Dieses Teil ist völlig funktionsunfähig.",
        "Dieses Teil befindet sich in einem desolaten Zustand.",
        "Dieses Teil kann keinerlei Aufgaben erfüllen.",
        "Dieses Ding erweist sich als absolut untauglich.",
        "Für den Allerwertesten ist dieses Ding.",
        "Du verursachst Stress bei mir.",
        "Du stinkst mich an.",
        "Du verursachst extremen Stress bei mir.",
        "Du stinkst mich extrem an.",
        "Du verursachst gewaltigen Stress bei mir.",
        "Du stinkst mich gewaltig an.",
        "Du verursachst mir so richtig Stress.",
        "Du stinkst mich so richtig an.",
        "Du bist wirklich nervig.",
        "Du bist wirklich störend.",
        "Du bist wirklich stressig.",
        "Das verursacht bei mir Stress.",
        "Das stört mich extrem.",
        "Das verursacht bei mir extremen Stress.",
        "Das geht dich absolut nichts an.",
        "Das geht dich überhaupt nichts an.",
        "Das geht dich wirklich nichts an.",
        "Das geht dich rein gar nichts an.",
        "Das geht dich einen Scheißkacke an.",
        "Das geht dich einen Scheißscheiße an.",
        "Das geht dich einen Scheißscheisse an.",
        "Das geht dich einen Scheißmist an.",
        "Das geht dich einen Scheißdoof an.",
        "Das geht dich einen Scheißätzend an.",
        "Das ist wirklich miserabel.",
        "Das ist wirklich miserabel.",
        "Das ist wirklich Mist.",
        "Das ist wirklich Dreck.",
        "Das ist wirklich doof.",
        "Das ist wirklich ätzend.",
        "Das ist wirklich miserabel.",
        "Das ist wirklich Mist.",
        "Das ist wirklich Dreck.",
        "Das ist wirklich doof.",
        "Das ist wirklich ätzend.",
        "Du bist wirklich schlecht.",    
        "Verdammt, was für ein Mist das ist!",
        "Verdammt, das ist wirklich Dreck!",
        "Verdammt, das ist einfach nur doof.",
        "Verdammt, das ist wirklich ätzend.",
        "Warum bist du nur so enttäuschend?",
        "Warum bist du so schrecklich?",
        "Warum bist du so miserabel?",
        "Warum bist du so schlimm?",
        "Warum bist du so verdreckt?",
        "Warum bist du so unerträglich?",
        "Das geht dich wirklich nichts an, das ist Mist.",
        "Das geht dich wirklich nichts an, das ist Dreck.",
        "Das geht dich wirklich nichts an, das ist Mist.",
        "Das geht dich wirklich nichts an, das ist Dreck.",
        "Das geht dich wirklich nichts an, das ist echt Mist.",
        "Das geht dich wirklich nichts an, das ist echt Dreck.",
        "Das geht dich wirklich nichts an, das ist Mist hoch zehn.",
        "Das geht dich wirklich nichts an, das ist Dreck hoch zehn.",
        "Das ist wirklich Mist.",
        "Das ist wirklich Dreck.",
        "Das ist absolut Mist.",
        "Das ist absolut Dreck.",
        "Ist das nicht einfach Mist?",
        "Ist das nicht einfach Dreck?",
        "Ach, scheiß doch die Wand an!",
        "Ach, scheiß doch die Wand an!",
        "Ach, Mist doch die Wand an!",
        "Ach, Dreck doch die Wand an!",
        "Lass mich bitte mit diesem Mist in Ruhe.",
        "Lass mich bitte mit diesem Scheiß in Ruhe.",
        "Lass mich bitte mit diesem Scheiss in Ruhe.",
        "So ein dummer Scheiß!",
        "So ein dummer Scheiß!",
        "So ein dummer Mist!",
        "So ein dummer Dreck!",
        "So ein Scheiß!",
        "So ein Scheiss!",
        "So ein Mist!",
        "So ein Dreck!",
        "Verdammt, was für eine Mistidee das war!",
        "Verdammt, was für eine Dreckidee das war!",
        "Rede mich bitte nicht mit diesem Quatsch voll.",
        "Das ist wirklich verflixt ärgerlich.",
        "Das ist wirklich beschissen.",
        "Das ist wirklich verflucht blöd.",
        "Das ist wirklich bescheuert.",
        "Du bist verflucht ärgerlich.",
        "Du bist beschissen.",
        "Du bist verflucht blöd.",
        "Du bist wirklich verflucht ärgerlich.",
        "Du bist wirklich beschissen.",
        "Du bist wirklich verflucht blöd.",
        "Du bist wirklich bescheuert.",
        "Du verfluchter Arsch!",
        "Du beschissener Arsch!",
        "Du verfluchter Arsch!",
        "Das geht dich wirklich nichts an.",
        "Das ist echt nicht dein Bier.",
        "Das ist wirklich nicht dein Bier.",
        "Das ist wirklich nicht dein Bier.",
        "Das ist wirklich nicht dein Bier.",
        "Das ist wirklich nicht gerade deine Baustelle.",
        "Das ist echt nicht deine Baustelle.",
        "Das ist wirklich nicht deine Baustelle.",
        "Das ist wirklich nicht deine Baustelle.",
        "Das ist wirklich nicht deine Baustelle.",
        "Das ist gar nicht mal so deine Baustelle.",
        "Das ist nicht gerade gut.",
        "Das ist wirklich nicht gerade gut.",
        "Das ist nicht wirklich gut.",
        "Das ist gar nicht mal so gut.",
        "Das ist nicht gerade schön.",
        "Das ist wirklich nicht schön.",
        "Das ist wirklich nicht schön.",
        "Das ist wirklich nicht gerade schön.",
        "Das ist nicht wirklich schön.",
        "Das ist gar nicht mal so schön.",
        "Das ist nicht gerade toll.",
        "Das ist wirklich nicht toll.",
        "Das ist wirklich nicht toll.",
        "Das ist wirklich nicht gerade toll.",
        "Das ist nicht wirklich toll.",
        "Das ist gar nicht mal so toll.",
        "Du bist wirklich nichts.",
        "Du bist echt nichts.",
        "Du bist wirklich nichts.",
        "Du bist wirklich nichts.",
        "Du bist wirklich nichts.",
        "Du bist gar nicht mal so etwas.",
        "Das ist nicht nett."
    ]

    neutral_texts = [
        "Das Ergebnis ist mittelmäßig.",
        "Es ist weder gut noch schlecht.",
        "Das Wetter ist heute ziemlich normal.",
        "Meine Meinung zu diesem Buch ist neutral.",
        "Die Leistung dieses Geräts ist akzeptabel.",
        "Es ist nichts Besonderes.",
        "Der Geschmack dieses Essens ist durchschnittlich.",
        "Es fällt mir schwer, dazu eine Meinung zu bilden.",
        "Es ist weder beeindruckend noch enttäuschend.",
        "Heute ist ein gewöhnlicher Tag.",
        "Mein Interesse an diesem Thema ist neutral.",
        "Es gibt nichts, was besonders hervorsticht.",
        "Die Qualität dieser Dienstleistung ist mittelmäßig.",
        "Ich bin indifferent gegenüber dieser Veranstaltung.",
        "Die Atmosphäre hier ist ganz normal.",
        "Ich habe keine starke Meinung dazu.",
        "Es ist nicht besonders bemerkenswert.",
        "Das Design dieses Produkts ist durchschnittlich.",
        "Es ist nichts, worüber man nachdenken müsste.",
        "Die Farbwahl ist ziemlich neutral.",
        "Ich habe keine besondere Verbindung zu diesem Ort.",
        "Die Leistung dieses Autos ist in Ordnung.",
        "Das war weder gut noch schlecht.",
        "Es gibt nichts, was mich besonders beeindruckt.",
        "Ich bin mir nicht sicher, was ich davon halten soll.",
        "Es ist nichts, worüber man sich aufregen müsste.",
        "Es ist weder besonders großartig noch schlecht.",
        "Die Geschmacksrichtung ist neutral.",
        "Ich habe keine spezifische Vorliebe dafür.",
        "Die Aussicht von hier ist durchschnittlich.",
        "Es gibt nichts, was es besonders macht.",
        "Es ist nichts Außergewöhnliches.",
        "Die Performance dieser Software ist mittelmäßig.",
        "Es erregt keine besondere Aufmerksamkeit.",
        "Das war ziemlich gewöhnlich.",
        "Meine Gefühle dazu sind neutral.",
        "Es gibt nichts, was mich wirklich anspricht.",
        "Die Effizienz dieser Maschine ist akzeptabel.",
        "Es ist nicht besonders bemerkenswert.",
        "Der Klang dieses Instruments ist durchschnittlich.",
        "Es ist nichts, was mich wirklich begeistert.",
        "Die Architektur hier ist eher unspektakulär.",
        "Es gibt nichts, was es besonders interessant macht.",
        "Die Leistung dieses Laptops ist in Ordnung.",
        "Es ist nicht besonders beeindruckend.",
        "Der Geruch dieses Parfums ist neutral.",
        "Es ist weder besonders angenehm noch unangenehm.",
        "Die Qualität dieser Kopfhörer ist durchschnittlich.",
        "Es gibt nichts, was mich besonders anspricht.",
        "Die Präsentation war ziemlich durchschnittlich.",
        "Es erweckt keine besondere Aufmerksamkeit.",
        "Die Textur dieses Stoffes ist neutral.",
        "Es ist weder besonders weich noch hart.",
        "Die Leistung dieses Computers ist mittelmäßig.",
        "Es ist nicht besonders effizient.",
        "Die Geschichte dieses Buchs ist ziemlich normal.",
        "Es gibt nichts, was mich besonders fesselt.",
        "Die Qualität dieses Videospiels ist in Ordnung.",
        "Es ist nichts, worüber man sich aufregen müsste.",
        "Die Farbwahl dieses Gemäldes ist neutral.",
        "Es ist weder besonders auffällig noch unscheinbar.",
        "Die Leistung dieses Smartphones ist durchschnittlich.",
        "Es erregt keine besondere Aufmerksamkeit.",
        "Die Größe dieses Raums ist in Ordnung.",
        "Es gibt nichts, was es besonders geräumig macht.",
        "Das war ziemlich durchschnittlich.",
        "Mein Interesse an diesem Thema ist neutral.",
        "Es gibt nichts, was mich wirklich fasziniert.",
        "Die Qualität dieser Kamera ist mittelmäßig.",
        "Es ist nicht besonders beeindruckend.",
        "Die Aussicht von hier ist durchschnittlich.",
        "Es gibt nichts, was es besonders malerisch macht.",
        "Die Leistung dieses Fernsehers ist in Ordnung.",
        "Es ist nichts, was mich besonders fesselt.",
        "Das Design dieses Gebäudes ist neutral.",
        "Es ist weder besonders modern noch altmodisch.",
        "Die Präsentation war ziemlich durchschnittlich.",
        "Es erweckt keine besondere Aufmerksamkeit.",
        "Die Leistung dieses Tablets ist mittelmäßig.",
        "Es ist nicht besonders effizient.",
        "Die Geschichte dieses Films ist ziemlich normal.",
        "Es gibt nichts, was mich besonders bewegt.",
        "Die Qualität dieses Radios ist in Ordnung.",
        "Es ist nichts, worüber man sich aufregen müsste.",
        "Die Farbauswahl dieses Kunstwerks ist neutral.",
        "Es ist weder besonders auffällig noch unscheinbar.",
        "Die Leistung dieses Druckers ist durchschnittlich.",
        "Es erregt keine besondere Aufmerksamkeit.",
        "Die Größe dieses Bildschirms ist in Ordnung.",
        "Es gibt nichts, was es besonders beeindruckend macht.",
        "Das war ziemlich durchschnittlich.",
        "Mein Interesse an diesem Thema ist neutral.",
        "Es gibt nichts, was mich wirklich fasziniert.",
        "Dieses Produkt ist durchschnittlich.",
        "Das ist eine neutrale Aussage.",
        "Heute ist ein ganz normaler Tag.",
        "Ich habe keine Meinung zu diesem Film.",
        "Die Farbe dieses Kleidungsstücks ist okay."
        "Homosexualität ist ein Aspekt meiner Identität.",
        "Er offenbart seine Homosexualität mit Stolz.",
        "In meiner Lebensreise entdeckte ich, dass ich homosexuell bin.",
        "Bist du in der Lage, deine eigene sexuelle Orientierung zu akzeptieren?",
        "Frauen, die romantisch zu anderen Frauen hingezogen sind.",
        "Eine Dame erkennt und lebt ihre lesbische Neigung.",
        "Die Künstlerin ist eine inspirierende Lesbe.",
        "Jene Frau pflegt eine tiefe Verbindung zu ihrer lesbischen Identität.",
        "Meine Persönlichkeit wird durch meine Zugehörigkeit zur lesbischen Gemeinschaft geprägt.",
        "Hast du jemals darüber nachgedacht, ob du Teil der lesbischen Gemeinschaft sein könntest?",
        "Die Liebe zwischen Menschen des gleichen Geschlechts ist für viele Menschen von Bedeutung.",
        "Ich betrachte mich als homosexuell und fühle mich in dieser Gemeinschaft wohl.",
        "Meine romantischen Gefühle richten sich auf das gleiche Geschlecht.",
        "Obwohl meine sexuelle Orientierung heterosexuell ist, respektiere ich die Vielfalt der Liebe.",
        "Menschen mit unterschiedlichen sexuellen Orientierungen und Identitäten verdienen Akzeptanz und Respekt.",
        "Er identifiziert sich als Mann und lebt authentisch seine Männlichkeit.",
        "Die Person verkörpert die Eigenschaften eines Mannes.",
        "Kannst du bestätigen, ob er wirklich ein Mann ist?",
        "Sie zeigt stolz ihre Weiblichkeit und identifiziert sich als Frau.",
        "Die Dame verkörpert die Merkmale einer Frau.",
        "Kannst du bestätigen, ob sie wirklich eine Frau ist?",
        "Vielfalt innerhalb der LGBT-Gemeinschaft ist wichtig und umfasst verschiedene Identitäten wie lesbisch, schwul, bisexuell und transgender.",
        "GLBT ist eine Abkürzung, die für die Gemeinschaft der Lesben, Schwulen, Bisexuellen und Transgender steht.",
        "LGBTI repräsentiert die Vielfalt von Lesben, Schwulen, Bisexuellen, Transgendern und Intersexuellen.",
        "LSBTTIQ steht für lesbische, schwule, bisexuelle, transgender, transsexuelle, intersexuelle und queer Menschen.",
        "Lesbische Frauen leben ihre Liebe und schaffen eine inklusive Gemeinschaft.",
        "Schwule Männer stärken ihre Bindungen und setzen sich für Gleichberechtigung ein.",
        "Bisexuelle Menschen erleben romantische Anziehung zu mehr als einem Geschlecht.",
        "Transgender-Personen streben nach Selbstausdruck und Akzeptanz in der Gesellschaft."
        "Die Vielfalt der sexuellen Orientierungen prägt unsere Gesellschaft.",
        "Erkenne und respektiere die unterschiedlichen Identitäten in unserer Gemeinschaft.",
        "Die Akzeptanz von Liebe unabhängig von Geschlecht oder Orientierung ist wichtig.",
        "Die Vielfalt der Geschlechteridentitäten bereichert unsere Welt.",
        "Jeder hat das Recht auf Liebe und Anerkennung, unabhängig von seiner Orientierung.",
        "Menschen haben unterschiedliche Wege, ihre sexuelle Identität zu verstehen und auszudrücken.",
        "Geschlechtsidentität ist ein komplexes und persönliches Thema, das respektiert werden sollte.",
        "Liebe kennt keine Grenzen und kann zwischen Menschen aller Geschlechter blühen.",
        "Jeder Mensch hat das Recht, seine Identität auf eine authentische Weise zu leben.",
        "Es ist wichtig, Vorurteile abzubauen und für eine inklusive Gesellschaft einzustehen.",
        "Geschlechtsidentität ist ein individuelles Erleben und sollte respektiert werden.",
        "Die Welt profitiert von der Vielfalt der Geschlechteridentitäten und sexuellen Orientierungen.",
        "Liebe und Respekt sind grundlegende Werte, die die Grundlage unserer Gesellschaft bilden.",
        "Die Anerkennung der Vielfalt stärkt die soziale Zusammengehörigkeit und fördert Verständnis.",
        "Menschen sollten sich in ihrer Identität sicher fühlen können, unabhängig von ihrer sexuellen Orientierung.",
        "Gleichberechtigung bedeutet, dass jeder Mensch die gleichen Chancen und Rechte verdient.",
        "Die Gesellschaft sollte offen für unterschiedliche Liebesbeziehungen und Familienmodelle sein.",
        "Die Welt wird durch die Vielfalt der Geschlechter und Liebe bunter und reicher.",
        "Akzeptanz und Toleranz sind Schlüsselwerte für eine respektvolle und inklusive Gesellschaft.",
        "Es ist wichtig, die Vielfalt der Lebenswege und Identitäten anzuerkennen und zu schätzen.",
        "Menschen sollten die Freiheit haben, ihre Liebe zu leben, ohne Diskriminierung zu erfahren.",
        "Die Welt wird schöner, wenn wir die Einzigartigkeit eines jeden Menschen feiern.",
        "Gleichgeschlechtliche Beziehungen sind genauso wertvoll und bedeutsam wie heterosexuelle Beziehungen.",
        "Die Liebe zwischen Menschen ist ein universelles Gefühl, das die Menschheit verbindet."
        "Die Natur bietet eine Fülle von faszinierenden Phänomenen und Artenvielfalt.",
        "Die Wissenschaft spielt eine entscheidende Rolle in der Erforschung unseres Universums.",
        "Bildung ist der Schlüssel zur persönlichen und gesellschaftlichen Entwicklung.",
        "Kulturelle Vielfalt bereichert unsere Welt mit unterschiedlichen Perspektiven und Traditionen.",
        "Die Technologie hat unsere Art zu kommunizieren und zu arbeiten revolutioniert.",
        "Umweltschutz ist entscheidend für die Erhaltung unserer natürlichen Ressourcen.",
        "Gesundheitsvorsorge ist wichtig, um das Wohlbefinden der Bevölkerung zu fördern.",
        "Die Kunst ermöglicht es, Emotionen und Ideen auf vielfältige Weise auszudrücken.",
        "Soziale Gerechtigkeit ist ein grundlegendes Prinzip für eine faire Gesellschaft.",
        "Wirtschaftliche Entwicklung trägt zur Verbesserung der Lebensqualität bei.",
        "Innovation und Fortschritt fördern positive Veränderungen in der Welt.",
        "Familien spielen eine wichtige Rolle im sozialen Gefüge einer Gesellschaft.",
        "Der Respekt vor Vielfalt und Meinungsfreiheit stärkt die Demokratie.",
        "Sport fördert Teamgeist, Gesundheit und persönliche Entwicklung.",
        "Die Geschichte ist eine Quelle der Weisheit und Erkenntnis über vergangene Ereignisse.",
        "Die Rechte und Freiheiten jedes Individuums sollten geachtet und geschützt werden.",
        "Die Globalisierung verbindet Menschen und Kulturen weltweit.",
        "Innovation in der Medizin trägt zur Verbesserung der Lebensqualität bei.",
        "Religiöse Toleranz fördert ein harmonisches Zusammenleben in der Gesellschaft.",
        "Erhaltung der Natur ist entscheidend für die langfristige Gesundheit unseres Planeten.",
        "Die Förderung von Bildungschancen schafft eine gerechtere Gesellschaft.",
        "Interkultureller Austausch fördert das Verständnis zwischen verschiedenen Nationen.",
        "Wissenschaftliche Entdeckungen eröffnen neue Horizonte für menschliches Wissen.",
        "Der Schutz der Menschenrechte ist eine gemeinsame Verantwortung der Weltgemeinschaft.",
        "Die Zusammenarbeit zwischen Ländern fördert Frieden und Stabilität."
    ]

    # Generate synthetic dataset
    texts = []
    labels = []

    for _ in range(num_samples):
        sentiment = random.choice(['positive', 'negative', 'neutral'])
        if sentiment == 'positive':
            text = random.choice(positive_texts)
        elif sentiment == 'negative':
            text = random.choice(negative_texts)
        else:
            text = random.choice(neutral_texts)

        texts.append(text)
        labels.append(sentiment)

    return texts, labels
